"""add parishioner_id to transactions

Revision ID: 1bbf07da2752
Revises: 80bf0d5a66ff
Create Date: 2025-08-07 07:11:52.971426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bbf07da2752'
down_revision: Union[str, Sequence[str], None] = '80bf0d5a66ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('parishioner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'parishioners', ['parishioner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'parishioner_id')
    # ### end Alembic commands ###
