"""create sacraments table

Revision ID: 6c09fc1e52b3
Revises: ffe4aab3fb6a
Create Date: 2025-08-07 09:14:20.785295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c09fc1e52b3'
down_revision: Union[str, Sequence[str], None] = 'ffe4aab3fb6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sacraments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parishioner_id', sa.Integer(), nullable=False),
    sa.Column('sacrament_type', sa.String(length=32), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('fee', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parishioner_id'], ['parishioners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sacraments_date'), 'sacraments', ['date'], unique=False)
    op.create_index(op.f('ix_sacraments_id'), 'sacraments', ['id'], unique=False)
    op.create_index(op.f('ix_sacraments_parishioner_id'), 'sacraments', ['parishioner_id'], unique=False)
    op.create_index(op.f('ix_sacraments_sacrament_type'), 'sacraments', ['sacrament_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sacraments_sacrament_type'), table_name='sacraments')
    op.drop_index(op.f('ix_sacraments_parishioner_id'), table_name='sacraments')
    op.drop_index(op.f('ix_sacraments_id'), table_name='sacraments')
    op.drop_index(op.f('ix_sacraments_date'), table_name='sacraments')
    op.drop_table('sacraments')
    # ### end Alembic commands ###
