"""add sacraments table

Revision ID: ffe4aab3fb6a
Revises: 9d9c1729c476
Create Date: 2025-08-07 09:09:11.989452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffe4aab3fb6a'
down_revision: Union[str, Sequence[str], None] = '9d9c1729c476'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parishioners', sa.Column('birth_date', sa.Date(), nullable=True))
    op.create_index(op.f('ix_parishioners_first_name'), 'parishioners', ['first_name'], unique=False)
    op.create_index(op.f('ix_parishioners_last_name'), 'parishioners', ['last_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parishioners_last_name'), table_name='parishioners')
    op.drop_index(op.f('ix_parishioners_first_name'), table_name='parishioners')
    op.drop_column('parishioners', 'birth_date')
    # ### end Alembic commands ###
